#!/bin/bash

# bashrc

[ -n "$PS1" ] && source ~/.bash_profile

# Load pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# 1password terminal plugins
source ~/.config/op/plugins.sh

# Added by Yarn Switch
source "~/.yarn/switch/env"

# Setup mise
eval "$("$BREW_HOME/bin/mise" activate bash)"
