#!/bin/bash

# bash_config

# Make vim the default editor
export EDITOR="vim"

# Ignore duplicate commands in the history
export HISTCONTROL=ignoredups

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

if [[ "$OSTYPE" == "darwin"* ]]; then
  # Export some paths
  export JAVA_HOME="`/usr/libexec/java_home -v 1.8`"

  # (be explicit in case Homebrew is not installed in the default location)
  export PHANTOMJS_BIN="$(brew --prefix)/bin/phantomjs"
  export ANDROID_HOME="$(brew --prefix)/Cellar/android-sdk/24.1.2"
fi

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Python virtual envs
export WORKON_HOME="~/.virtualenvs"

# Ruby gems
GEM_HOME="${HOME}/.gems"

# NPM packages
export NVM_DIR="${HOME}/.nvm"
source $(brew --prefix nvm)/nvm.sh
NPM_PACKAGES="${HOME}/.npm-packages"
NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
