#!/bin/bash

# bashrc

[ -n "$PS1" ] && source ~/.bash_profile

# Load pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Setup Volta
export VOLTA_HOME="$HOME/.volta"
grep --silent "$VOLTA_HOME/bin" <<< $PATH || export PATH="$VOLTA_HOME/bin:$PATH"
