#!/bin/zsh

load_dotfiles() {
    declare -a files=(
        "$HOME/.dotfiles/shell/bash_aliases"
        "$HOME/.dotfiles/shell/bash_exports"
        "$HOME/.zshrc.local"
    )

    # if these files are readable, source them
    for file in ${files[@]}
    do
        if [ -r $file ]; then
            source $file
        fi
    done
}

load_dotfiles
unset load_dotfiles

eval "$(pyenv init -)"

# Load Autocompletion
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
fi

ZSH_THEME="robbyrussell"
[[ -f ~/.oh-my-zsh/oh-my-zsh.sh ]] && source ~/.oh-my-zsh/oh-my-zsh.sh

# 1password terminal plugins
source /Users/simon.boudrias/.config/op/plugins.sh
