#!/bin/zsh

load_dotfiles() {
    declare -a files=(
        "$HOME/.dotfiles/shell/bash_aliases"
        "$HOME/.dotfiles/shell/bash_exports"
        "$HOME/.zshrc.local"
    )

    # if these files are readable, source them
    for file in ${files[@]}
    do
        if [ -r $file ]; then
            source $file
        fi
    done
}

load_dotfiles
unset load_dotfiles

export BREW_HOME="${BREW_HOME:-/opt/homebrew}"

# Load Autocompletion
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
fi

ZSH_THEME="robbyrussell"
plugins=(git-auto-fetch)
ZSH_DISABLE_COMPFIX=true
[[ -f ~/.oh-my-zsh/oh-my-zsh.sh ]] && source ~/.oh-my-zsh/oh-my-zsh.sh

# 1password terminal plugins
[ -r "$HOME/.config/op/plugins.sh" ] && source "$HOME/.config/op/plugins.sh"

# Setup mise
eval "$("$BREW_HOME/bin/mise" activate zsh)"
