source $HOME/.dotfiles/shell/bash_aliases
source $HOME/.dotfiles/shell/bash_exports
source $HOME/.dotfiles/shell/zsh_paths

eval "$(pyenv init -)"

# Load Autocompletion
[ -f `brew --prefix`/etc/bash_completion ] && . `brew --prefix`/etc/bash_completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
export PATH="/usr/local/sbin:$PATH"

# Setup Volta
export VOLTA_HOME="$HOME/.volta"
grep --silent "$VOLTA_HOME/bin" <<< $PATH || export PATH="$VOLTA_HOME/bin:$PATH"

[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export GPG_TTY=$(tty)
