#!/bin/bash

run_brew() {

    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Updating Homebrew..."
        # Use the latest version of Homebrew
        brew update
        [[ $? ]] && e_success "Done"

        e_header "Updating any existing Homebrew formulae..."
        # Upgrade any already-installed formulae
        brew upgrade
        [[ $? ]] && e_success "Done"

        e_header "Checking status of desired Homebrew formulae..."
        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            'coreutils' # GNU core utilities (those that come with OS X are outdated)
            'git'
            'ack'
            'bash'
            'bash-completion'
            'ffmpeg'
            'graphicsmagick'
            'jpeg'
            'macvim --override-system-vim'
            'optipng'
            'tree'
            'wget'
            'yarn'
            'watchman'
        )

        for index in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
            fi
        done

        if [[ "$missing_formulae" ]]; then
            # Convert the array of missing formula into a list of space-separate strings
            list_formulae=$( printf "%s " "${missing_formulae[@]}" )

            e_header "Installing missing Homebrew formulae..."
            # Install all missing formulae
            brew install $list_formulae

            [[ $? ]] && e_success "Done"
        fi

        # use latest rsync rather than out-dated OS X rsync
        # install separately from the main formulae list to fix gh-19
        brew install https://raw.github.com/Homebrew/homebrew-dupes/master/rsync.rb

        e_header "Checking status of desired Homebrew cask..."
        local list_cask
        local -a missing_cask
        local -a desired_cask=(
            'atom'
            'iterm2'
            'docker' # docker for mac
            'alfred'
            'spectacle'
            '1password'
            'google-backup-and-sync'
            'evernote'
            'spotify'
            'google-chrome'
            'electronic-wechat'
        )

        for index in ${!desired_cask[*]}
        do
            if ! cask_exists ${desired_cask[$index]}; then
                # Store the name (and options) of every missing formula
                missing_cask=("${missing_cask[@]}" "${desired_cask[$index]}")
            fi
        done

        if [[ "$missing_cask" ]]; then
            # Convert the array of missing casks into a list of space-separate strings
            list_cask=$( printf "%s " "${missing_cask[@]}" )

            e_header "Installing missing Homebrew cask..."
            # Install all missing cask
            brew cask install $list_cask

            [[ $? ]] && e_success "Done"
        fi

        # Remove outdated versions from the Cellar
        brew cleanup
        brew cask cleanup
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        printf "Go to https://brew.sh/"
        exit
    fi
}
