#!/bin/bash

run_brew() {

    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Updating Homebrew..."
        # Use the latest version of Homebrew
        brew update
        [[ $? ]] && e_success "Done"

        e_header "Updating any existing Homebrew formulae..."
        # Upgrade any already-installed formulae
        brew upgrade
        [[ $? ]] && e_success "Done"

        e_header "Checking status of desired Homebrew formulae..."
        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            'coreutils' # GNU core utilities (those that come with OS X are outdated)
            'git'
            'git-delta'
            'gh'
            'ack'
            'bash'
            'bash-completion'
            'delta'
            'zsh-completions'
            'ffmpeg'
            'graphicsmagick'
            'jpeg'
            'vim'
            'optipng'
            'tree'
            'volta'
            'wget'
            'watchman'
        )

        for index in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
            fi
        done

        if [[ "$missing_formulae" ]]; then
            # Convert the array of missing formula into a list of space-separate strings
            list_formulae=$( printf "%s " "${missing_formulae[@]}" )

            e_header "Installing missing Homebrew formulae..."
            # Install all missing formulae
            echo brew install --formulae $list_formulae
            brew install --formulae $list_formulae

            [[ $? ]] && e_success "Done"
        fi

        e_header "Checking status of desired Homebrew cask..."
        local list_cask
        local -a missing_cask
        local -a desired_cask=(
            'docker' # docker for mac
            'raycast'
            'rectangle'
            '1password'
            'google-drive'
            'spotify'
            'google-chrome'
            'wechat'
            'whatsapp'
            'messenger'
            'warp'
            'visual-studio-code'
        )

        for index in ${!desired_cask[*]}
        do
            if ! cask_exists ${desired_cask[$index]}; then
                # Store the name (and options) of every missing formula
                missing_cask=("${missing_cask[@]}" "${desired_cask[$index]}")
            fi
        done

        if [[ "$missing_cask" ]]; then
            # Convert the array of missing casks into a list of space-separate strings
            list_cask=$( printf "%s " "${missing_cask[@]}" )

            e_header "Installing missing Homebrew cask..."
            # Install all missing cask
            echo brew install --cask $list_cask
            brew install --cask $list_cask

            [[ $? ]] && e_success "Done"
        fi

        chmod go-w "$(brew --prefix)/share"
        chmod -R go-w "$(brew --prefix)/share/zsh"
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        printf "Go to https://brew.sh/"
        exit
    fi
}
