#!/bin/bash

run_brew() {

    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Updating Homebrew..."
        # Use the latest version of Homebrew
        brew update
        [[ $? ]] && e_success "Done"

        e_header "Updating any existing Homebrew formulae..."
        # Upgrade any already-installed formulae
        brew upgrade
        [[ $? ]] && e_success "Done"

        e_header "Checking status of desired Homebrew formulae..."
        local list_brew
        local -a missing_brew
        local -a desired_formulae=(
            'coreutils' # GNU core utilities (those that come with OS X are outdated)
            'git'
            'ack'
            'bash'
            'bash-completion'
            'ffmpeg'
            'graphicsmagick'
            'jpeg'
            'vim'
            'optipng'
            'tree'
            'wget'
            'yarn'
            'watchman'
        )

        for index in ${!desired_formulae[*]}
        do
            if ! formula_or_cask_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                missing_brew=("${missing_brew[@]}" "${desired_formulae[$index]}")
            fi
        done

        e_header "Checking status of desired Homebrew cask..."
        local -a desired_cask=(
            'docker' # docker for mac
            'alfred'
            'spectacle'
            '1password'
            'google-drive'
            'evernote'
            'spotify'
            'google-chrome'
            'electronic-wechat'
            'whatsapp'
            'messenger'
            'warp'
            'visual-studio-code'
        )

        for index in ${!desired_cask[*]}
        do
            if ! formula_or_cask_exists ${desired_cask[$index]}; then
                # Store the name (and options) of every missing formula
                missing_brew=("${missing_brew[@]}" "${desired_cask[$index]}")
            fi
        done

        if [[ "$missing_brew" ]]; then
            # Convert the array of missing brews into a list of space-separate strings
            list_brew=$( printf "%s " "${missing_brew[@]}" )

            e_header "Installing missing Homebrew formulae..."
            # Install all missing formulae
            brew install $list_brew

            [[ $? ]] && e_success "Done"
        fi

        # use latest rsync rather than out-dated OS X rsync
        # install separately from the main formulae list to fix gh-19
        brew install https://raw.github.com/Homebrew/homebrew-dupes/master/rsync.rb

        # Remove outdated versions from the Cellar
        brew cleanup
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        printf "Go to https://brew.sh/"
        exit
    fi
}
