#!/bin/bash

run_npm() {

    # Check for mise
    if type_exists 'mise'; then
        e_header "Installing Node.js packages..."

        # List of npm packages
        local packages="npm:yo@latest npm:ipt@latest"

        # Install packages globally through mise
        if mise use -g -y $packages; then
            e_success "Done"
        else
            exit 1
        fi
    else
        printf "\n"
        e_error "Error: mise not found."
        printf "Aborting...\n"
        exit
    fi

}
